use utf8;

package Lilith::Schema;

# Created by DBIx::Class::Schema::Loader
# DO NOT MODIFY THE FIRST PART OF THIS FILE

use strict;
use warnings;

use base 'DBIx::Class::Schema';

__PACKAGE__->load_namespaces;

# Created by DBIx::Class::Schema::Loader v0.07049 @ 2026-03-15 20:03:16
# DO NOT MODIFY THIS OR ANYTHING ABOVE! md5sum:aO+/s2fYL0UYzF6bG0ldZA

our $VERSION = 14;

=head1 NAME

Lilith::Schema - the DBIx::Class schema behind the Lilith database.

=head1 SYNOPSIS

    my $schema = Lilith::Schema->connect( $dsn, $user, $pass );
    my $rs     = $schema->resultset('SuricataAlert');

=head1 DESCRIPTION

The result classes under L<Lilith::Schema::Result> and the migrations that
deploy them. Everything above the loader's marker is generated by
L<DBIx::Class::Schema::Loader> and is not edited by hand; the schema is changed
by altering the database and regenerating, then writing the migration for the
step.

Lilith itself only uses this for the parts that suit a result class: searching
the alert tables, and C<lilith deploy> / C<lilith migrate>. The hand written
SQL elsewhere in L<Lilith> -- escalation, auto escalation, the receiver keys,
the dashboards -- goes through DBI directly, so this schema is not the whole
picture of what is in the database.

=head1 VERSION

C<$VERSION> is the B<schema> version, a plain incrementing integer rather than
a dotted release version, and it is what L<DBIx::Class::Migration> deploys and
upgrades against. It has nothing to do with the version of Lilith itself: a
release that changes no tables leaves it alone.

The matching migrations live under C<share/migrations>, and
C<lilith schema_version> reports what a database carries against what this
release expects. See L<docs/install.md|https://github.com/LilithSec/Lilith/blob/main/docs/install.md>
for deploying and upgrading.

=head1 SEE ALSO

L<Lilith>, L<DBIx::Class::Schema>, L<DBIx::Class::Migration>

=cut

1;
