#!/usr/bin/env perl

=head1 NAME

lilith-web - Mojolicious web frontend for Lilith.

=head1 SYNOPSIS

lilith-web daemon

lilith-web daemon -l http://*:8080

LILITH_CONFIG=/etc/lilith.toml lilith-web daemon

=head1 DESCRIPTION

Starts the Lilith web frontend using Mojolicious. The config file is read
from C<LILITH_CONFIG> env var, defaulting to C</usr/local/etc/lilith.toml>.

Supports all standard Mojolicious server commands (daemon, prefork, etc).

=head1 SEE ALSO

L<Mojolicious::Commands>, L<Lilith::Web>

=cut

use strict;
use warnings;
use FindBin qw($Bin);
use lib "$Bin/../lib";
use Mojolicious::Commands;

Mojolicious::Commands->start_app('Lilith::Web');
