#!/bin/sh

# PROVIDE: mojo_lilith
# REQUIRE: LOGIN postgresql
# KEYWORD: shutdown
#
#
#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf to enable the
# Lilith web frontend:
# mojo_lilith_enable (bool):   Set to "NO" by default.
#                              Set it to "YES" to enable mojo_lilith.
# mojo_lilith_user (string):   Set to "lilith" by default. User to run as.
# mojo_lilith_listen (string): Set to "http://127.0.0.1:8080" by default.
#                              The URL(s) to listen on.
# mojo_lilith_config (string): Set to "/usr/local/etc/lilith.toml" by default.
#                              Path to the Lilith config, exported as
#                              LILITH_CONFIG.
# mojo_lilith_flags (string):  Set to "" by default. Extra flags appended to
#                              the mojo command.

. /etc/rc.subr

name=mojo_lilith
rcvar=${name}_enable

load_rc_config $name

# set defaults
: ${mojo_lilith_enable:=NO}
: ${mojo_lilith_user:="lilith"}
: ${mojo_lilith_listen:="http://127.0.0.1:8080"}
: ${mojo_lilith_config:="/usr/local/etc/lilith.toml"}
: ${mojo_lilith_flags:=""}

pidfile="/var/run/${name}/pid"

# rc.subr exports ${name}_env into the command's environment
mojo_lilith_env="LILITH_CONFIG=${mojo_lilith_config}"

# Mojolicious apps run in the foreground; supervise with daemon(8), which drops
# to the unprivileged user, restarts the worker if it dies, and owns the pid.
command="/usr/sbin/daemon"
command_args="-P ${pidfile} -r -f -u ${mojo_lilith_user} \
    /usr/local/bin/${name} prefork -l ${mojo_lilith_listen} ${mojo_lilith_flags}"
start_precmd="${name}_precmd"

mojo_lilith_precmd()
{
    if [ ! -d "/var/run/${name}" ]; then
        mkdir -p "/var/run/${name}"
    fi
    chown "${mojo_lilith_user}" "/var/run/${name}"
}

load_rc_config $name
run_rc_command "$1"
